name: CD

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: docker compose build
    