name: CD

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker-compose build