name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker-compose build auth
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker images
      run: echo "Push images to hub"
    - name: SSH to run VM script
      run: echo "SSH to run VM script"
    - name: Build Docker Image Clean-up
      run: docker-compose down --rmi all