name: CI
on: push

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use NodeJS
      uses: actions/setup-node@v2
    - name: Install Yarn
      run: npm install -g yarn
    - run: yarn 
    - run: yarn test