name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use NodeJS
      uses: actions/setup-node@v2
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn test