name: CI
on: push

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
    - uses: actions/checkout@v4
    - name: Use NodeJS
      uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install yarn
      run: npm install -g yarn
    - run: yarn install
    - run: yarn test